config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :categories do
    resources :transfers
  end

  resources :users

  root to: "homes#index", as: 'auth_login'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :manage, :all
    else
      cannot :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :transfers, foreign_key: 'category_id', dependent: :destroy
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category, class_name: 'Category'

  validates :name, presence: true
  validates :amount, presence: true, comparison: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transfers, foreign_key: 'author_id', dependent: :destroy
  has_many :categories, foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Category.where(user_id: current_user.id)
    @name = 'Categories'
  end

  def new
    category = Category.new
    render :new, locals: { category: }
  end

  def create
    @category = Category.new(params.require(:new_category).permit(:name, :icon))
    @category.user = current_user
    if @category.save
      flash[:notice] = 'Category successfully created'
      redirect_to categories_path
    else
      flash[:alert] = @category.errors.full_messages.join(', ')
      render 'new', locals: { category: @category }
    end
  end

  def show
    @transfers = Transfer.where(author_id: current_user.id, category_id: params[:id]).order(:created_at).reverse_order
    @name = 'TRANSFERS'
    @category_id = params[:id]
    @category = Category.find(@category_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    render :index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  load_and_authorize_resource

  def new
    transfer = Transfer.new
    @categories = Category.where(user_id: current_user.id)
    render :new, locals: { transfer:, categories: @categories }
  end

  def create
    @transfer = Transfer.new(name: params[:new_transfer][:name], amount: params[:new_transfer][:amount])
    category = params[:new_transfer][:category]
    @transfer.category = Category.find(category.to_i)
    @transfer.author = current_user
    if @transfer.save
      flash[:notice] = 'Object successfully created'
      redirect_to category_path(@transfer.category.id)
    else
      flash[:alert] = 'Something went wrong'
      @categories = Category.where(user_id: current_user.id)
      render 'new', locals: { transfer:, categories: @categories }
    end
  end

  def transfer_params
    params.require(:new_transfer).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = 'Profile'
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<%= link_to category_path(category.id),class:"link-container" do %>
<div class="card mb-3 mt-2 container-categories">
  <div class="row g-0">
    <div class="col responsive-image">
      <img src="<%= category.icon %>" class="img-fluid img-responsive rounded-start" alt="...">
    </div>
    <div class="col">
      <div class="card-body">
        <div class="d-flex justify-content-between">
        <h5 class="card-title text-muted text-dark"><%= category.name %></h5>
        <% amount = 0 %>
        <% category.transfers.each do |transfer| %>
            <% amount += transfer.amount %>
        <% end %>
        <p class="card-text cash-text">$<%= amount %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/categories/index.html.erb
<div class="transfer-list-flex-container">
<% @categories.each do |category| %>
    <%= render category %>
<% end %>
<% if @categories.length == 0 %>
    <div>
        <p class="display-4">No categories found.</p>
    <div>
<% end %>
</div>
<div class="w-100 btn-holder">
<%= link_to "Add Category" ,new_category_path,data: { turbolinks: 'false' }, class:"btn btn-success w-100  make-transfers" %>
</div>


app/views/categories/new.html.erb
<%= form_with model: category, method: :post, url: categories_path ,scope: :new_category, local:true do |form| %>
    <h3 class="display-3">Create Category</h3>
    <hr>
    <div class="mb-3">
        <%= form.label :name,class:"form-label"%>
        <%= form.text_field :name,class:"form-control", :required => true %>
    </div>
    <div>
        <%= form.label :icon, class:"form-label" %>
        <%= form.text_field :icon, class:"form-control", :required => true %>
    </div>
    <div class="mb-3 text-center">
        <%= form.submit "Add Category",disable_with:"Creating Category...",data: { turbolinks: 'false' }, class:"btn btn-success" %>
    </div>
<% end %>

app/views/categories/show.html.erb
<div class="d-flex justify-content-between transfer-flex-container">
    <h5><%= @category.name %></h5>
    <% amount = 0%>
    <% @transfers.each do |transfer| %>
    <% amount += transfer.amount %>
    <% end %>
    <strong>$<%= amount %></strong>
</div>
<div class="container-fluid  transfer-list-flex-container mt-4">
    <div class="transfers-holder">
    <% if @transfers.length != 0 %>
        <% @transfers.each do |transfer| %>
            <%= render transfer %>
        <% end %>
    <% else %>
        <div>
            <h6>No transactions found</h6>
        </div>
    <%end%>
    <div>
    <div class="w-100 btn-holder">
    <%= link_to "Scan" ,new_category_transfer_path(@category_id), class:"btn btn-success w-100 mt-3 make-transfers" %>
    </div>
</div>


app/views/homes/index.html.erb
<div class="auth-login-container">
<h1 class="display-1 logo-name text-dark">PaymentsIQ</h1>
<div></div>
<div class="auth-login-form-container">
    <%= link_to "LOG IN", new_user_session_path,class:"btn btn-primary w-100 my-2" %>
    <%= link_to "SIGN UP",new_user_registration_path, class:"btn btn-light w-100 my-2"%>
</div>
</div>

app/views/layouts/_header.html.erb
<nav>
  <% if user_signed_in?%>
        <ul id="nav-menu">
          <li class="nav-link"><%= link_to "Home", categories_path %></li>
          <li class="nav-link"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li class="nav-link">
          <%= link_to  destroy_user_session_path, method: :get do %>
                Sign Out
          <% end %>
          </li>
        </ul>
        <div id="mobile-navbar">
        <div class="top-nav-container d-flex justify-content-between">
          <% if @name == "Categories" %>
          <div id="hamb">
            <span class="bar fs-3 m-2"></span>
            <span class="bar fs-3 m-2"></span>
            <span class="bar fs-3 m-2"></span>
          </div>
          <% else %>
            <%= link_to categories_path,class:"link-container arrow-back-link" do %>
                <i class="fa-solid fa-arrow-left-long"></i>
            <% end %>
          <% end %>
          <div class="current-page">
            <span><%= @name %></span>
          </div>
          <div class="search-icon">
            <i class="fa-solid fa-magnifying-glass fs-3 m-3"></i>
          </div>
          </div>
          <ul id="mobile-nav-menu">
            <li class="mobile-nav-link"><%= link_to "Home", categories_path %></li>
            <li class="nav-link">
            <%= link_to user_path(current_user.id) do %>
                <i class="nav-profile-pic fa-solid fa-user"></i>
            <% end %>
            </li>
            <li class="mobile-nav-link">
              <%= link_to  destroy_user_session_path, method: :get do %>
                <i class="fa-solid fa-right-from-bracket"></i>
              <% end %>
            </li>
            <li class="mobile-nav-link">Signed in as <%= current_user.email %></li>
          </ul>
    </div>
    <% else %>
      <% if current_page?(new_user_session_path)%>
      <div class="d-flex mx-2 justify-content-between">
        <%= link_to auth_login_path,class:"link-container arrow-back-link" do %>
                <i class="fa-solid fa-arrow-left-long"></i>
        <% end %>
        <p class="text-light fs-3 align-self-start py-2">LOGIN</p>
        <div id="login-btn-touch">
          <p class="fs-3">Login</p>
        </div>
      </div>
      <script>
        document.querySelectorAll('#login-btn-touch').forEach((link) => {
            link.addEventListener('click',() => {
                const login_form = document.querySelector('#login-form-sub')
                login_form.submit()
            })
        })
      </script>
      <% else %>
        <div class="d-flex mx-2 justify-content-between">
        <%= link_to auth_login_path,class:"link-container arrow-back-link" do %>
                <i class="fa-solid fa-arrow-left-long"></i>
        <% end %>
        <p class="text-light fs-3 align-self-start py-2">SIGN UP</p>
        <div id="signup-btn-touch">
          <p class="fs-3">Next</p>
        </div>
        <script>
        document.querySelectorAll('#signup-btn-touch').forEach((link) => {
            link.addEventListener('click',() => {
                const login_form = document.querySelector('#register-form-controll')
                login_form.submit()
            })
        })
      </script>
      </div>
      <% end %>
    <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentsIQ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-visit-control" content="reload">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/2cde69ef6f.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
        <%= render 'layouts/header' %>
    </header>
    <div class="container">
    <% if not flash.empty? %>
      <% if flash[:notice] %>
      <div class="alert alert-info" role="alert"><%= notice %></div>
      <% else %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
    <% end %>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/transfers/_transfer.html.erb
<div class="card w-100 mb-3">
  <div class="card-body d-flex justify-content-between p-4">
    <image src="<%= transfer.category.icon %>" class="transfer-image-responsive"></image>
    <div class="title-date-container">
      <h5 class="card-title"><%= transfer.name %></h5>
      <% date = transfer.created_at %>
      <% date = date.strftime('%b/%d/%Y') %>
      <p><%= date %></p>
    </div>
    <strong>$<%= transfer.amount%></strong>
  </div>
</div>

app/views/transfers/new.html.erb
<%= form_with model: transfer, method: :post, url: category_transfers_path(params[:category_id]) ,scope: :new_transfer, local:true do |form| %>
    <h3 class="display-3">Make Transfers</h3>
    <hr>
    <div class="mb-3">
        <%= form.label :name,class:"form-label"%>
        <%= form.text_field :name,class:"form-control", :required => true %>
    </div>
    <div>
        <%= form.label :amount, class:"form-label" %>
        <%= form.number_field :amount,in:1.0..1000000.0, class:"form-control", :required => true %>
    </div>
    <div class="mt-3">
        <%= form.label :category, class:"form-label" %>
        <%= form.collection_select :category,categories,:id,:name, class:"form-control", :required => true %>
    </div>
    <div class="mb-3 text-center">
        <%= form.submit "Transfer",disable_with:"Making Transfer...", class:"btn btn-success" %>
    </div>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
    <h4 class="display-4">Welcome To PaymentsIQ</h4>
    <span class="logo-name quote-logo">Simple Outrageous Payment</span>
    <div class="flex-field-container">
        <i class="fa-regular fa-user"></i>
        <p><%= current_user.name %></p>
    </div>
    <div class="flex-field-container">
        <i class="fa-regular fa-envelope"></i>
        <p><%= current_user.email %></p>
    </div>
</div>